In [2]:
# investor demographics - age group distribution pie chart SIP amount boxplot by age group . gender split
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

investor_df = pd.read_csv("../data/processed/08_investor_transactions_clean.csv",
                          parse_dates=['transaction_date'])
investor_df.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [3]:
investor_df['age_group'].value_counts()

age_group
26-35    13463
36-45     8146
18-25     4916
46-55     3779
56+       2474
Name: count, dtype: int64

In [4]:
age_counts = investor_df['age_group'].value_counts()

fig = px.pie(
    values= age_counts.values,
    names = age_counts.index,
    title='Investor distribution by age group'
)

fig.show()

In [5]:
# SIP AMOUNT BOX PLOT BY AGE GROUP - how much does each group invest

sip_Transactions = investor_df[investor_df['transaction_type'] == 'SIP']

In [6]:
fig = px.box(
    sip_Transactions,
    x='age_group',
    y='amount_inr',
    title = 'SIP amount distribution by age group',

    labels={
        'amount_inr':"Amount",
        'age_group': 'Age Group'
    }

)
fig.show()

In [7]:
# gender split

investor_df['gender'].value_counts()

gender
Male      21809
Female    10969
Name: count, dtype: int64

In [8]:
gender_counts = investor_df['gender'].value_counts()

fig = px.pie(
    values= gender_counts.values,
    names= gender_counts.index,
    title='Investor distribution by gender'
)
fig.show()

In [9]:
# Analysis 6: Geographic Distribution

In [10]:
#Horizontal Bar Chart → SIP Amount by State

In [12]:
investor_df.head()

,investor_id,transaction_date,amfi_code,transaction_type,amount_inr,state,city,city_tier,age_group,gender,annual_income_lakh,payment_mode,kyc_status
0,INV003054,2024-01-01,119092,SIP,1834,Telangana,Hyderabad,T30,56+,Female,77.1,UPI,Verified
1,INV002952,2024-01-01,148567,Redemption,392882,Punjab,Amritsar,B30,18-25,Male,7.1,Cheque,Verified
2,INV003420,2024-01-01,118636,SIP,912,Haryana,Faridabad,B30,36-45,Male,47.2,Mandate,Verified
3,INV003436,2024-01-01,118634,SIP,1102,Maharashtra,Mumbai,T30,36-45,Female,54.4,Cheque,Pending
4,INV004691,2024-01-01,119094,Lumpsum,8682,Delhi,Noida,T30,26-35,Male,14.5,Net Banking,Pending

In [13]:
investor_df['state'].value_counts()

state
Punjab            2965
Madhya Pradesh    2931
Tamil Nadu        2806
Gujarat           2780
West Bengal       2748
Haryana           2736
Telangana         2718
Uttar Pradesh     2695
Delhi             2677
Karnataka         2621
Rajasthan         2577
Maharashtra       2524
Name: count, dtype: int64

In [16]:
sip_amount_by_state = (
    investor_df[investor_df['transaction_type'] == 'SIP']
    .groupby('state')['amount_inr']
    .sum()
    .sort_values(ascending=False)
)

sip_amount_by_state

state
Madhya Pradesh    20682243
Punjab            20140064
Telangana         18620216
Tamil Nadu        18404368
Gujarat           18378904
Haryana           18176696
Karnataka         17696903
Uttar Pradesh     17534858
West Bengal       17495769
Delhi             17113608
Rajasthan         16544233
Maharashtra       16445629
Name: amount_inr, dtype: int64

In [17]:
# bar chart of SIP amount by state
fig = px.bar(
    sip_amount_by_state,
    x=sip_amount_by_state.index,
    y=sip_amount_by_state.values,
    title='SIP Amount by State',
    labels={
        'x': 'State',
        'y': 'SIP Amount (INR)'
    }
)
fig.show()

In [19]:
# Pie Chart → T30 vs B30 City Tier
city_tier_counts = investor_df['city_tier'].value_counts()
city_tier_counts

city_tier
T30    21719
B30    11059
Name: count, dtype: int64

In [20]:
fig = px.pie(
    values= city_tier_counts.values,
    names= city_tier_counts.index,
    title='Investor distribution by City Tier'
)
fig.show()